version: '3'

services:
  jaeger:
    networks:
      - backend
    image: 'jaegertracing/all-in-one:latest'
    volumes:
      - ./jaeger-ui.json:/etc/jaeger/jaeger-ui.json
    command: ["--query.ui-config=/etc/jaeger/jaeger-ui.json"]
    environment:
      - METRIC_STORAGE_TYPE=prometheus
      - PROMETHEUS_SERVER_URL=http://prometheus:9090
    ports:
      - "14250:14250"
      - "14268:14268"
      - "6831:6831/udp"
      - "16686:16686"
      - "16685:16685"
    
  otel_collector:
    networks:
      - backend
    image: 'otel/opentelemetry-collector-contrib:latest'
    volumes:
      - "./otel-collector-config.yml:/etc/otelcol/otel-collector-config.yml"
    command: ["--config=/etc/otelcol/otel-collector-config.yml"]
    ports:
      - "14278:14278"
      - "55677:55677"
    depends_on:
      - jaeger

  prometheus: 
    networks:
      - backend
    image: 'prom/prometheus'
    command: ["--config.file=/prometheus-config/prometheus.yml"]
    volumes:
      - ./prometheus-config:/prometheus-config
    ports:
      - "9090:9090"

  grafana:
    networks:
      - backend
    image: 'grafana/grafana-oss:latest-ubuntu'
    volumes:
      - ./grafana/config:/etc/grafana
      - ./grafana/logs:/var/log/grafana
      - ./grafana/data:/var/lib/grafana
    ports:
      - "3000:3000"

networks:
  backend:
