global:
  scrape_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
    - targets: 
      - localhost:9090

  - job_name: 'my_app_instrumented'
    scrape_interval: 5s
    static_configs:
    - targets:
      - localhost:8080

  - job_name: aggregated-trace-metrics
    scrape_interval: 5s
    static_configs:
    - targets:
      - otel_collector:8889 
